name: Deploy

on:
  workflow_call:
    inputs:
      aws-region:
        default: 'us-east-1'
        required: false
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  tests:
    runs-on: ubuntu-20.04
    # with:
    #   aws-region: ${{ inputs.aws-region }}
    # secrets:
    #   aws-access-key-id: ${{ secrets.aws-access-key-id }}
    #   aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
    steps:
      - run: echo "Done deploy"
