name: Deploy

on:  workflow_call
# on:
#   workflow_call:
#     inputs:
#       aws-region:
#         default: 'us-east-1'
#         required: false
#         type: string
#     secrets:
#       aws-access-key-id:
#         required: true
#       aws-secret-access-key:
#         required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - run: aws s3 ls sfx7697wsh9t
