name: Run End-To-End

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  tests:
    needs: build
    uses: vovko/vovko/.github/workflows/tests.yml@master

  # aws-configure:
  #   uses: aws-actions/configure-aws-credentials@v1
  #   with:
  #     aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
  #     aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  #     aws-region: us-east-1

  # deploy:
  #   needs: aws-configure
  #   uses: vovko/vovko/.github/workflows/deploy.yml@master