name: Run End-To-End

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  test:
    uses: vovko/vovko/.github/workflows/test.yml@e64354b601132d59abae29f1b5f38a5b1006dc82

  deploy:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Done deploy"