name: Run End-To-End

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        uses: vovko/vovko/.github/workflows/tests.yml@master

  deploy:
    needs: tests
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Done deploy"