name: Production Deployment

on:
  push:
    tags:
      - release-*

jobs:
  tests:
    uses: vovko/vovko/.github/workflows/tests.yml@master

  release:
    needs: tests
    uses: vovko/vovko/.github/workflows/release.yml@master
    secrets:
      aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}

  deploy:
    needs: release
    uses: vovko/vovko/.github/workflows/deploy.yml@master
    secrets:
      aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
