name: Pull Request Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  tests:
    needs: build
    uses: vovko/vovko/.github/workflows/tests.yml@master
