name: Run Tests

on: workflow_call

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Tests'
        run: make tests
